apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
  labels:
    app: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: moukthikavuyyuru/chat-app:latest  # replace with your Docker Hub username and image name
        ports:
        - containerPort: 8080  # replace with the port your app runs on
